# Generated by Django 4.1.4 on 2023-01-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('details', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='photo/%y/%m/%d')),
                ('required_fund', models.PositiveIntegerField()),
            ],
        ),
    ]
