# Generated by Django 4.1.4 on 2023-01-01 21:40

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('card_number', models.CharField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='photo/%y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(null=True, upload_to='photo/%y/%m/%d'),
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_value', models.PositiveIntegerField()),
                ('date_of_investment', models.DateField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='core.campaign')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='core.customer')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.customer'),
            preserve_default=False,
        ),
    ]
