# Generated by Django 4.1.4 on 2023-01-11 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_myuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
